// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {context} from '../models';

export function GetFilePreview(arg1:string):Promise<gui.PreviewData>;

export function GetQuickTargets():Promise<Record<string, string>>;

export function ListFiles(arg1:string):Promise<Array<gui.FileEntry>>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function Quit():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function TrashFile(arg1:string):Promise<void>;
