// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['gui']['Controller']['CheckForUpdates'](arg1);
}

export function EmptyTrash() {
  return window['go']['gui']['Controller']['EmptyTrash']();
}

export function FindDuplicates(arg1) {
  return window['go']['gui']['Controller']['FindDuplicates'](arg1);
}

export function GetFilePreview(arg1) {
  return window['go']['gui']['Controller']['GetFilePreview'](arg1);
}

export function GetMediaServerURL() {
  return window['go']['gui']['Controller']['GetMediaServerURL']();
}

export function GetQuickTargets() {
  return window['go']['gui']['Controller']['GetQuickTargets']();
}

export function GetTrashPath() {
  return window['go']['gui']['Controller']['GetTrashPath']();
}

export function ListFiles(arg1) {
  return window['go']['gui']['Controller']['ListFiles'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['gui']['Controller']['MoveFile'](arg1, arg2);
}

export function OpenNative(arg1) {
  return window['go']['gui']['Controller']['OpenNative'](arg1);
}

export function PickDirectory() {
  return window['go']['gui']['Controller']['PickDirectory']();
}

export function PinTarget(arg1) {
  return window['go']['gui']['Controller']['PinTarget'](arg1);
}

export function Quit() {
  return window['go']['gui']['Controller']['Quit']();
}

export function Startup(arg1) {
  return window['go']['gui']['Controller']['Startup'](arg1);
}

export function TrashFile(arg1) {
  return window['go']['gui']['Controller']['TrashFile'](arg1);
}
